### ISSUE TITLE
URL in console logs

### ISSUE THREAD

**Issue by jbednar** [JosephCottam/AbstractRendering#76]
Right now, the server console has output like:

Processing request: /CENSUS_NY_SYN_PEOPLE?width=860&height=500&requesterID=hq-dhcp-20-65.corp.continuum.io:48352&allowStretch=True&aggregator=COC_COMP&arl=(present(rgb,0,23,100))&latlon=-125;23;-65;50;

It would be useful if this could be prepended with the hostname and portname, to make it be a valid URL.  I often find myself cutting and pasting from the server console to try different options, and having it be immediately pasteable as a URL would be helpful, as in:

Processing request: http:localhost:6582/CENSUS_NY_SYN_PEOPLE?width=860&height=500&requesterID=hq-dhcp-20-65.corp.continuum.io:48352&allowStretch=True&aggregator=COC_COMP&arl=(present(rgb,0,23,100))&latlon=-125;23;-65;50;

**Comment by JosephCottam** [comment]
Checked in on the server branch.

**Comment by jbednar** [comment]
Thanks!
